### ISSUE TITLE
fisheye webhook 문제 해결기 블로그 쓰기

### ISSUE THREAD

**Issue by pineoc** [pineoc/study#26]
## fisheye webhook

https://confluence.atlassian.com/fisheye/configuring-web-hooks-960155631.html

## 에러 문구

```
POST /test/webhook 415 4.796 ms - 1426
UnsupportedMediaTypeError: unsupported content encoding "utf-8"
    at contentstream (C:\Users\pineoc\Desktop\private\pino-bot\node_modules\body-parser\lib\read.js:174:13)
    at read (C:\Users\pineoc\Desktop\private\pino-bot\node_modules\body-parser\lib\read.js:54:14)
    at jsonParser (C:\Users\pineoc\Desktop\private\pino-bot\node_modules\body-parser\lib\types\json.js:134:5)
    at Layer.handle [as handle_request] (C:\Users\pineoc\Desktop\private\pino-bot\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\pineoc\Desktop\private\pino-bot\node_modules\express\lib\router\index.js:317:13)
    at C:\Users\pineoc\Desktop\private\pino-bot\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Users\pineoc\Desktop\private\pino-bot\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\pineoc\Desktop\private\pino-bot\node_modules\express\lib\router\index.js:275:10)
    at logger (C:\Users\pineoc\Desktop\private\pino-bot\node_modules\morgan\index.js:144:5)
    at Layer.handle [as handle_request] (C:\Users\pineoc\Desktop\private\pino-bot\node_modules\express\lib\router\layer.js:95:5)
```

## 해결 방법

- https://github.com/expressjs/body-parser/issues/100
- Content-encoding 이라는 헤더 값은 invalid한 내용이라 아래 내용을 파싱하기 전에 지워주었다.

```js
//...
app.use(function (req, res, next) {
  // remove invalid header
  delete req.headers['content-encoding'];
  next();
});
app.use(express.json());
app.use(express.urlencoded({ extended: false }));
// ...
```

## 참고

- fisheye webhook은 post 방식으로 데이터를 받고 있음

**Comment by pineoc** [comment]
https://pineoc.github.io/blog/2019/04/20/fisheye-webhook-error/

작성완료!
